### ISSUE TITLE
Make e-mail formatting cleaner

### ISSUE THREAD

**Issue by packetcat** [packetcat/lazyreddit#5]
The current formatting of the e-mail being sent is really crappy, clean up and remove unnecessary stuff.

**Comment by foxiepaws** [comment]
yes it is **REALLY** crappy. Make it look all nice and HTMLified :>

(just kidding please don't kill me)

**Comment by packetcat** [comment]
I really am not sure how to go about making it nice either.
- Stripping extraneous brackets and commas
- Indentation etc.
